/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Agm12105tgRouteImport } from './routes/agm-12105tg'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindYourBatteryRouteImport } from './routes/find-your-battery'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as TransportationRouteImport } from './routes/transportation'
import { Route as CategoriesHealthcareMobilityRouteImport } from './routes/categories/healthcare-mobility'
import { Route as CategoriesMaterialHandlingIndustrialRouteImport } from './routes/categories/material-handling-industrial'
import { Route as CategoriesOfficeBackupPowerUpsRouteImport } from './routes/categories/office-backup-power-ups'
import { Route as CategoriesRoboticsAutomationRouteImport } from './routes/categories/robotics-automation'
import { Route as CategoriesTransportationLeisureRouteImport } from './routes/categories/transportation-leisure'
import { Route as CategoriesUtilityVehiclesRouteImport } from './routes/categories/utility-vehicles'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ProductsPartRouteImport } from './routes/products.$part'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Agm12105tgRoute = Agm12105tgRouteImport.update({
  id: '/agm-12105tg',
  path: '/agm-12105tg',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindYourBatteryRoute = FindYourBatteryRouteImport.update({
  id: '/find-your-battery',
  path: '/find-your-battery',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportationRoute = TransportationRouteImport.update({
  id: '/transportation',
  path: '/transportation',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesHealthcareMobilityRoute =
  CategoriesHealthcareMobilityRouteImport.update({
    id: '/categories/healthcare-mobility',
    path: '/categories/healthcare-mobility',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesMaterialHandlingIndustrialRoute =
  CategoriesMaterialHandlingIndustrialRouteImport.update({
    id: '/categories/material-handling-industrial',
    path: '/categories/material-handling-industrial',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesOfficeBackupPowerUpsRoute =
  CategoriesOfficeBackupPowerUpsRouteImport.update({
    id: '/categories/office-backup-power-ups',
    path: '/categories/office-backup-power-ups',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesRoboticsAutomationRoute =
  CategoriesRoboticsAutomationRouteImport.update({
    id: '/categories/robotics-automation',
    path: '/categories/robotics-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesTransportationLeisureRoute =
  CategoriesTransportationLeisureRouteImport.update({
    id: '/categories/transportation-leisure',
    path: '/categories/transportation-leisure',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesUtilityVehiclesRoute =
  CategoriesUtilityVehiclesRouteImport.update({
    id: '/categories/utility-vehicles',
    path: '/categories/utility-vehicles',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPartRoute = ProductsPartRouteImport.update({
  id: '/products/$part',
  path: '/products/$part',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agm-12105tg': typeof Agm12105tgRoute
  '/contact': typeof ContactRoute
  '/find-your-battery': typeof FindYourBatteryRoute
  '/specs': typeof SpecsRoute
  '/transportation': typeof TransportationRoute
  '/categories/healthcare-mobility': typeof CategoriesHealthcareMobilityRoute
  '/categories/material-handling-industrial': typeof CategoriesMaterialHandlingIndustrialRoute
  '/categories/office-backup-power-ups': typeof CategoriesOfficeBackupPowerUpsRoute
  '/categories/robotics-automation': typeof CategoriesRoboticsAutomationRoute
  '/categories/transportation-leisure': typeof CategoriesTransportationLeisureRoute
  '/categories/utility-vehicles': typeof CategoriesUtilityVehiclesRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/products/$part': typeof ProductsPartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agm-12105tg': typeof Agm12105tgRoute
  '/contact': typeof ContactRoute
  '/find-your-battery': typeof FindYourBatteryRoute
  '/specs': typeof SpecsRoute
  '/transportation': typeof TransportationRoute
  '/categories/healthcare-mobility': typeof CategoriesHealthcareMobilityRoute
  '/categories/material-handling-industrial': typeof CategoriesMaterialHandlingIndustrialRoute
  '/categories/office-backup-power-ups': typeof CategoriesOfficeBackupPowerUpsRoute
  '/categories/robotics-automation': typeof CategoriesRoboticsAutomationRoute
  '/categories/transportation-leisure': typeof CategoriesTransportationLeisureRoute
  '/categories/utility-vehicles': typeof CategoriesUtilityVehiclesRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/products/$part': typeof ProductsPartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agm-12105tg': typeof Agm12105tgRoute
  '/contact': typeof ContactRoute
  '/find-your-battery': typeof FindYourBatteryRoute
  '/specs': typeof SpecsRoute
  '/transportation': typeof TransportationRoute
  '/categories/healthcare-mobility': typeof CategoriesHealthcareMobilityRoute
  '/categories/material-handling-industrial': typeof CategoriesMaterialHandlingIndustrialRoute
  '/categories/office-backup-power-ups': typeof CategoriesOfficeBackupPowerUpsRoute
  '/categories/robotics-automation': typeof CategoriesRoboticsAutomationRoute
  '/categories/transportation-leisure': typeof CategoriesTransportationLeisureRoute
  '/categories/utility-vehicles': typeof CategoriesUtilityVehiclesRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/products/$part': typeof ProductsPartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agm-12105tg'
    | '/contact'
    | '/find-your-battery'
    | '/specs'
    | '/transportation'
    | '/categories/healthcare-mobility'
    | '/categories/material-handling-industrial'
    | '/categories/office-backup-power-ups'
    | '/categories/robotics-automation'
    | '/categories/transportation-leisure'
    | '/categories/utility-vehicles'
    | '/docs/$slug'
    | '/products/$part'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agm-12105tg'
    | '/contact'
    | '/find-your-battery'
    | '/specs'
    | '/transportation'
    | '/categories/healthcare-mobility'
    | '/categories/material-handling-industrial'
    | '/categories/office-backup-power-ups'
    | '/categories/robotics-automation'
    | '/categories/transportation-leisure'
    | '/categories/utility-vehicles'
    | '/docs/$slug'
    | '/products/$part'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agm-12105tg'
    | '/contact'
    | '/find-your-battery'
    | '/specs'
    | '/transportation'
    | '/categories/healthcare-mobility'
    | '/categories/material-handling-industrial'
    | '/categories/office-backup-power-ups'
    | '/categories/robotics-automation'
    | '/categories/transportation-leisure'
    | '/categories/utility-vehicles'
    | '/docs/$slug'
    | '/products/$part'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Agm12105tgRoute: typeof Agm12105tgRoute
  ContactRoute: typeof ContactRoute
  FindYourBatteryRoute: typeof FindYourBatteryRoute
  SpecsRoute: typeof SpecsRoute
  TransportationRoute: typeof TransportationRoute
  CategoriesHealthcareMobilityRoute: typeof CategoriesHealthcareMobilityRoute
  CategoriesMaterialHandlingIndustrialRoute: typeof CategoriesMaterialHandlingIndustrialRoute
  CategoriesOfficeBackupPowerUpsRoute: typeof CategoriesOfficeBackupPowerUpsRoute
  CategoriesRoboticsAutomationRoute: typeof CategoriesRoboticsAutomationRoute
  CategoriesTransportationLeisureRoute: typeof CategoriesTransportationLeisureRoute
  CategoriesUtilityVehiclesRoute: typeof CategoriesUtilityVehiclesRoute
  DocsSlugRoute: typeof DocsSlugRoute
  ProductsPartRoute: typeof ProductsPartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agm-12105tg': {
      id: '/agm-12105tg'
      path: '/agm-12105tg'
      fullPath: '/agm-12105tg'
      preLoaderRoute: typeof Agm12105tgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-your-battery': {
      id: '/find-your-battery'
      path: '/find-your-battery'
      fullPath: '/find-your-battery'
      preLoaderRoute: typeof FindYourBatteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportation': {
      id: '/transportation'
      path: '/transportation'
      fullPath: '/transportation'
      preLoaderRoute: typeof TransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/healthcare-mobility': {
      id: '/categories/healthcare-mobility'
      path: '/categories/healthcare-mobility'
      fullPath: '/categories/healthcare-mobility'
      preLoaderRoute: typeof CategoriesHealthcareMobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/material-handling-industrial': {
      id: '/categories/material-handling-industrial'
      path: '/categories/material-handling-industrial'
      fullPath: '/categories/material-handling-industrial'
      preLoaderRoute: typeof CategoriesMaterialHandlingIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/office-backup-power-ups': {
      id: '/categories/office-backup-power-ups'
      path: '/categories/office-backup-power-ups'
      fullPath: '/categories/office-backup-power-ups'
      preLoaderRoute: typeof CategoriesOfficeBackupPowerUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/robotics-automation': {
      id: '/categories/robotics-automation'
      path: '/categories/robotics-automation'
      fullPath: '/categories/robotics-automation'
      preLoaderRoute: typeof CategoriesRoboticsAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/transportation-leisure': {
      id: '/categories/transportation-leisure'
      path: '/categories/transportation-leisure'
      fullPath: '/categories/transportation-leisure'
      preLoaderRoute: typeof CategoriesTransportationLeisureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/utility-vehicles': {
      id: '/categories/utility-vehicles'
      path: '/categories/utility-vehicles'
      fullPath: '/categories/utility-vehicles'
      preLoaderRoute: typeof CategoriesUtilityVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$part': {
      id: '/products/$part'
      path: '/products/$part'
      fullPath: '/products/$part'
      preLoaderRoute: typeof ProductsPartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Agm12105tgRoute: Agm12105tgRoute,
  ContactRoute: ContactRoute,
  FindYourBatteryRoute: FindYourBatteryRoute,
  SpecsRoute: SpecsRoute,
  TransportationRoute: TransportationRoute,
  CategoriesHealthcareMobilityRoute: CategoriesHealthcareMobilityRoute,
  CategoriesMaterialHandlingIndustrialRoute:
    CategoriesMaterialHandlingIndustrialRoute,
  CategoriesOfficeBackupPowerUpsRoute: CategoriesOfficeBackupPowerUpsRoute,
  CategoriesRoboticsAutomationRoute: CategoriesRoboticsAutomationRoute,
  CategoriesTransportationLeisureRoute: CategoriesTransportationLeisureRoute,
  CategoriesUtilityVehiclesRoute: CategoriesUtilityVehiclesRoute,
  DocsSlugRoute: DocsSlugRoute,
  ProductsPartRoute: ProductsPartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
